### ISSUE TITLE
Can you add the option of a Wolfram alpha API and an additional chain of thought example using it ?

### ISSUE THREAD

**Issue by ogkalu2** [minosvasilias/toolformer-zero#1]

**Comment by minosvasilias** [comment]
Adding wolfram to the mix should definitely be possible. It might blur the lines between calculator and search tools somewhat, but seeing how the model handles that would be interesting to observe in itself.

Would generally not like to complicate the setup process too much with more API keys, but adding some optional ones could work. I'll see when i can get to it, otherwise contributions are always welcome. :)

**Comment by minosvasilias** [comment]
This should be resolved by #9 . :)
Best results achievable when disabling Google search, though that will also result in some requests wolfram can not handle.

There's the possibility of more sophisticated implementations using the [Full Results API](https://products.wolframalpha.com/api/documentation), the [Fast Query Recognizer API](https://products.wolframalpha.com/query-recognizer/documentation) (which did not work for me when testing) or the upcoming [LLM API](https://products.wolframalpha.com/api), which sounds like it would be tailor made for this purpose.
